openapi: 3.0.3

info:
  title: Slim Test API
  description: API de gestion des utilisateurs.
  version: 1.0.0

servers:
  - url: http://localhost:8000

paths:
  /api/test:
    get:
      summary: Api de test
      description: api de test.
      requestBody:
        required: false
      responses:
        '200':
          description: test.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: hello world
  /api/register:
    post:
      summary: Inscription d'un utilisateur
      description: Crée un nouveau compte utilisateur.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  maxLength: 32
                  description: Nom d'utilisateur.
                  example: Guillaume

                email:
                  type: string
                  format: email
                  maxLength: 255
                  description: Adresse email de l'utilisateur.
                  example: guillaume@example.com

                password:
                  type: string
                  maxLength: 32
                  format: password
                  description: Mot de passe de l'utilisateur.
                  example: Password123!

      responses:
        '201':
          description: Utilisateur créé avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ok

        '400':
          description: Les données envoyées sont invalides.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Les données ne sont pas valident
  /api/login:
    post:
      summary: Connexion utilisateur
      description: Permet à un utilisateur de se connecter.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 255
                  description: Adresse email de l'utilisateur.
                  example: guillaume@example.com

                password:
                  type: string
                  maxLength: 32
                  format: password
                  description: Mot de passe de l'utilisateur.
                  example: Password123!
      responses:
        '201':
          description: Utilisateur connecté avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: connexion réussi

        '400':
          description: Connexion impossible.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Le mot de passe ou l'email est incorrect
  /api/logout:
    post:
      summary: Déconnexion d'un utilisateur
      description: Permet à un utilisateur de se déconnecter.
      responses:
        '200':
          description: L'utilisateur est connecté.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Déconnexion réussi

        '400':
          description: L'utilisateur n'est pas connecté.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: vous n'êtes pas connecté. 